// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/d60-Lab/gin-template/internal/api/handler"
)

// Injectors from wire.go:

// InitializeApp 初始化整个应用
func InitializeApp() (*App, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := ProvideDatabase(config)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(db)
	userService := ProvideUserService(userRepository, config)
	modelClients := ProvideAIModelClients()
	aiService := ProvideAIService(modelClients)
	handler := ProvideHandler(userService)
	aiHandler := ProvideAIHandler(aiService)
	app := NewApp(handler, aiHandler)
	return app, nil
}

// wire.go:

// App 应用容器
type App struct {
	Handler   *handler.Handler
	AIHandler *handler.AIHandler
}

// NewApp 创建 App 实例
func NewApp(h *handler.Handler, aiH *handler.AIHandler) *App {
	return &App{Handler: h, AIHandler: aiH}
}
