// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/d60-Lab/gin-template/internal/api/handler"
)

func InitializeApp() (*App, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := ProvideDatabase(config)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(db)
	userService := ProvideUserService(userRepository, config)
	modelClients := ProvideAIModelClients()
	aiService := ProvideAIService(modelClients)
	practiceRouteRepository := ProvidePracticeRouteRepository(db)
	practiceRouteService := ProvidePracticeRouteService(practiceRouteRepository)
	questionRepository := ProvideQuestionRepository(db)
	questionService := ProvideQuestionService(questionRepository)
	h := ProvideHandler(userService)
	aiHandler := ProvideAIHandler(aiService)
	practiceRouteHandler := ProvidePracticeRouteHandler(practiceRouteService)
	questionHandler := ProvideQuestionHandler(questionService)
	app := NewApp(h, aiHandler, practiceRouteHandler, questionHandler)
	return app, nil
}

type App struct {
	Handler              *handler.Handler
	AIHandler            *handler.AIHandler
	PracticeRouteHandler *handler.PracticeRouteHandler
	QuestionHandler      *handler.QuestionHandler
}

func NewApp(h *handler.Handler, aiH *handler.AIHandler, prH *handler.PracticeRouteHandler, qH *handler.QuestionHandler) *App {
	return &App{Handler: h, AIHandler: aiH, PracticeRouteHandler: prH, QuestionHandler: qH}
}
