INSERT INTO tag (name, category) VALUES
('Java', '编程语言'), ('MySQL', '数据库'), ('Redis', '数据库'), ('Spring', '框架'),
('SpringBoot', '框架'), ('SpringCloud', '框架'), ('计算机网络', '基础'), ('操作系统', '基础'),
('消息队列', '中间件'), ('后端系统设计', '架构'), ('AI大模型', '人工智能'), ('JVM', 'Java'),
('集合', 'Java'), ('并发', 'Java'), ('Go', '编程语言'), ('Python', '编程语言'),
('C++', '编程语言'), ('前端', '编程语言'), ('算法', '基础'), ('数据库', '基础');

INSERT INTO question_bank (name, description, icon, category, is_vip, question_count, sort) VALUES
('Java 热门面试题 200 道', '2026 最新 Java 热门面试题 200 道，涵盖 Java、MySQL、Redis、Spring、SpringBoot、SpringCloud、计算机网络、操作系统、消息队列等', '☕', 'Java', false, 200, 1),
('Java 基础面试题', 'Java 作为广泛应用的编程语言，基础扎实是后端开发的关键。', '☕', 'Java', false, 50, 2),
('Java 集合面试题', 'Java 集合框架是后端开发中处理数据结构的核心模块之一。', '☕', 'Java', false, 40, 3),
('Java 并发面试题', 'Java 并发编程是高性能应用开发的重要环节。', '☕', 'Java', false, 35, 4),
('AI 大模型面试题', '2026最全面、答案最详细的AI大模型应用开发面试题库。', '🤖', '人工智能', false, 30, 5),
('Java 虚拟机面试题', 'JVM 是 Java 程序运行的核心，是性能优化与问题排查的基础。', '☕', 'Java', false, 30, 6),
('MySQL 面试题', 'MySQL 是主流的开源关系型数据库管理系统，是后端开发者必备的技能。', '🗄️', '数据库', false, 45, 7),
('Redis 面试题', 'Redis 是流行的分布式缓存数据库，在高性能系统中广泛应用。', '🗄️', '数据库', false, 35, 8),
('Spring 面试题', 'Spring 是 Java 企业级开发的核心框架之一。', '🌱', '框架', false, 30, 9),
('SpringBoot 面试题', 'SpringBoot 是构建微服务和快速开发企业级应用的重要框架。', '🌱', '框架', false, 25, 10),
('SpringCloud 面试题', 'SpringCloud 是微服务架构下的服务治理框架。', '☁️', '框架', false, 25, 11),
('计算机网络面试题', '计算机网络是信息系统的通信基础。', '🌐', '基础', false, 30, 12),
('操作系统面试题', '操作系统是计算机系统管理与资源调度的核心。', '💻', '基础', false, 25, 13),
('消息队列面试题', '消息队列是分布式系统中解耦与削峰的关键技术。', '📬', '中间件', false, 20, 14),
('后端系统设计面试题', '后端系统设计是构建大规模、高可用服务的核心能力。', '🏗️', '架构', false, 20, 15);

INSERT INTO question (title, content, difficulty, is_vip, view_count, star_count, like_count, answer, explanation) VALUES
('HashMap 的底层实现原理是什么？', 'HashMap 是 Java 中最常用的数据结构之一，其底层基于数组+链表+红黑树实现。', 2, false, 12580, 890, 1200, 'HashMap 基于哈希表实现，JDK 1.8 之后采用数组+链表+红黑树的数据结构。当链表长度超过 8 且数组长度超过 64 时，链表会转换为红黑树以提高查询效率。put 过程：先计算 hash 值定位桶位置，如果桶为空直接插入，否则遍历链表或红黑树进行更新或插入。扩容时默认容量翻倍，重新计算每个元素的位置。', 'HashMap 是面试高频考点，核心在于理解哈希冲突的解决方式和扩容机制。JDK 1.8 引入红黑树是重要优化，需要掌握链表转红黑树的阈值条件。还需要了解 HashMap 的线程安全问题，为什么推荐使用 ConcurrentHashMap 替代。'),
('ArrayList 和 LinkedList 的区别是什么？', 'ArrayList 基于动态数组实现，支持随机访问；LinkedList 基于双向链表实现，插入和删除效率高。', 1, false, 9870, 650, 890, 'ArrayList 基于动态数组实现，随机访问 O(1)，插入删除需要移动元素 O(n)。LinkedList 基于双向链表实现，插入删除 O(1)（已知位置），随机访问 O(n)。ArrayList 内存占用更紧凑，LinkedList 每个节点额外存储前后指针。实际开发中 ArrayList 使用更多。', 'ArrayList vs LinkedList 是 Java 集合的经典对比题。除了基本区别，面试官可能追问扩容机制、遍历方式、内存占用等细节。实际开发中 ArrayList 使用频率远高于 LinkedList，这是一个重要结论。'),
('Java 中的 final、finally、finalize 有什么区别？', 'final 用于修饰类、方法和变量；finally 是异常处理中的代码块；finalize 是 Object 类的方法。', 2, false, 8650, 520, 730, 'final 修饰类表示不可继承，修饰方法表示不可重写，修饰变量表示不可修改。finally 是 try-catch-finally 中的代码块，无论是否异常都会执行。finalize 是 Object 类的方法，在 GC 回收对象前调用，JDK 9 已标记为废弃。', '这道题考察 Java 基础的扎实程度。final 是最常用的，需要理解其修饰不同元素的含义。finally 主要用于资源释放。finalize 已被废弃，不推荐使用，推荐使用 try-with-resources 或 Cleaner 机制替代。'),
('线程池的核心参数有哪些？', '线程池的核心参数包括：corePoolSize、maximumPoolSize、keepAliveTime、workQueue、threadFactory、handler。', 2, false, 11200, 780, 1050, 'corePoolSize 核心线程数、maximumPoolSize 最大线程数、keepAliveTime 空闲线程存活时间、unit 时间单位、workQueue 工作队列、threadFactory 线程工厂、handler 拒绝策略。执行流程：核心线程 → 队列 → 非核心线程 → 拒绝策略。', '线程池是 Java 并发的核心考点。七大参数必须牢记，执行流程（核心线程→队列→非核心线程→拒绝策略）是面试重点。四种拒绝策略的区别和应用场景也需要掌握。实际项目中推荐使用自定义线程池而非 Executors 工具类。'),
('JVM 垃圾回收算法有哪些？', 'JVM 的垃圾回收算法主要包括：标记-清除算法、复制算法、标记-整理算法、分代收集算法。', 3, false, 7890, 620, 870, '标记-清除算法：产生内存碎片。复制算法：新生代使用，将内存分为 Eden 和两个 Survivor 区，效率高但浪费空间。标记-整理算法：老年代使用，解决碎片问题。分代收集算法：根据对象存活时间分代，不同代使用不同算法。常见垃圾收集器：Serial、Parallel、CMS、G1、ZGC。', 'JVM 垃圾回收是 Java 高级面试必考题。四种算法各有优缺点，需要结合分代模型理解。CMS、G1、ZGC 等收集器的特点和使用场景是区分候选人水平的关键。建议结合 JVM 调优实战经验来回答。'),
('Spring Boot 自动配置原理是什么？', 'Spring Boot 自动配置的核心是 @EnableAutoConfiguration 注解。', 3, false, 9560, 710, 980, 'Spring Boot 通过 @EnableAutoConfiguration 注解开启自动配置，利用 SpringFactoriesLoader 加载 META-INF/spring.factories 中的配置类，根据 @Conditional 系列注解的条件判断来决定是否生效。核心是 spring-boot-autoconfigure 模块。', 'Spring Boot 自动配置原理是 Spring 全家桶的核心考点。需要理解 @Conditional 系列注解的条件判断机制，以及 spring.factories 的加载过程。建议结合自定义 Starter 来加深理解。'),
('Spring 中 Bean 的生命周期？', 'Spring Bean 的生命周期包括：实例化、属性赋值、初始化、使用、销毁。', 2, false, 8230, 580, 790, 'Spring Bean 的完整生命周期：1）实例化（createBeanInstance）；2）属性赋值（populateBean）；3）Aware 接口回调；4）BeanPostProcessor 前置处理；5）InitializingBean.afterPropertiesSet；6）自定义 init-method；7）BeanPostProcessor 后置处理；8）使用；9）DisposableBean.destroy；10）自定义 destroy-method。', 'Bean 生命周期是 Spring 框架的核心考点。需要重点掌握 BeanPostProcessor 和 Aware 接口的作用。面试中常结合 AOP 的实现原理来考察，BeanPostProcessor 是 AOP 代理创建的关键。'),
('MySQL 索引的底层数据结构是什么？', 'MySQL InnoDB 引擎使用 B+ 树作为索引的底层数据结构。', 2, false, 10500, 750, 1020, 'B+ 树相比 B 树和二叉树，具有更矮的树高，磁盘 I/O 次数更少。叶子节点通过链表相连，支持范围查询。非叶子节点只存储键值，单个节点能存储更多键值，从而降低树的高度。B+ 树的查询性能稳定，每次查询都需要走到叶子节点，路径长度相同。', 'B+ 树是数据库索引的核心数据结构，面试常考。需要对比 B 树、B+ 树、红黑树、跳表的优劣。重点理解为什么数据库不用红黑树（树太高，磁盘 I/O 多）和为什么不用跳表（范围查询不如 B+ 树高效）。'),
('Redis 的数据类型有哪些？', 'Redis 支持 5 种基本数据类型：String、List、Set、ZSet、Hash。', 1, false, 8900, 600, 820, 'Redis 支持 5 种基本数据类型：String（字符串）、List（列表）、Set（集合）、ZSet（有序集合）、Hash（哈希）。Redis 6.0+ 还新增了 Stream 类型。String 底层使用 SDS，List 底层使用 quicklist，Set 底层使用 intset 或 hashtable，ZSet 底层使用 ziplist 或 skiplist+hashtable，Hash 底层使用 ziplist 或 hashtable。', 'Redis 数据类型是基础必考题。除了五种基本类型，还需要了解各类型的底层数据结构实现（SDS、跳表、压缩列表等）。面试常追问每种类型的适用场景和底层实现。'),
('TCP 三次握手的过程是什么？', 'TCP 三次握手：1）客户端发送 SYN；2）服务器返回 SYN+ACK；3）客户端发送 ACK。', 2, false, 7650, 540, 750, '三次握手：客户端发送 SYN=1, seq=x → 服务端回复 SYN=1, ACK=1, seq=y, ack=x+1 → 客户端发送 ACK=1, seq=x+1, ack=y+1。四次挥手：主动方发送 FIN → 被动方回复 ACK → 被动方发送 FIN → 主动方回复 ACK 并进入 TIME_WAIT 状态等待 2MSL。', 'TCP 三次握手和四次挥手是网络基础必考题。三次握手的核心是确认双方的收发能力，四次挥手是因为 TCP 全双工通信需要双方各自关闭。TIME_WAIT 状态的作用和 2MSL 等待时间也是常见追问。'),
('什么是 CAP 定理？', 'CAP 定理指出分布式系统不可能同时满足一致性、可用性和分区容错性。', 2, false, 6780, 480, 660, 'CAP 定理指出分布式系统不可能同时满足一致性(Consistency)、可用性(Availability)和分区容错性(Partition tolerance)，最多只能同时满足其中两个。由于网络分区必然存在，所以实际是在 CP 和 AP 之间选择。ZooKeeper 是 CP 系统，Eureka 是 AP 系统。', 'CAP 定理是分布式系统的基础理论。面试中常结合具体系统（如 ZooKeeper、Eureka、Nacos）考察 CP 和 AP 的选择。还需要了解 BASE 理论和最终一致性概念。'),
('Kafka 如何保证消息不丢失？', 'Kafka 通过生产者 acks=all、Broker 副本机制、消费者手动提交 offset 保证消息不丢失。', 2, false, 5670, 420, 580, '生产者端：使用确认机制(confirm)、本地消息表保障消息发出。MQ端：持久化存储、集群部署、主从复制。消费者端：手动ACK确认、幂等性处理防止重复消费。RocketMQ 的事务消息可以保证分布式事务的最终一致性。', '消息可靠性是消息队列的核心考点。需要从生产者、MQ、消费者三端分析消息丢失的场景和解决方案。RocketMQ 的事务消息和 Kafka 的 Exactly-Once 语义是进阶考点。'),
('ConcurrentHashMap 的实现原理？', 'JDK 1.8 改为 CAS + synchronized，锁粒度更细。', 3, false, 9200, 690, 950, 'JDK 1.7 使用 Segment 分段锁，每个 Segment 继承 ReentrantLock。JDK 1.8 改为 CAS + synchronized，锁粒度从 Segment 级别细化到桶（Node）级别。put 流程：1）计算 hash 定位桶；2）桶为空则 CAS 写入；3）桶不为空则 synchronized 锁定头节点后操作；4）链表长度>=8 转红黑树。size 方法使用 baseCount + CounterCell 实现。', 'ConcurrentHashMap 是 Java 并发编程的经典考题。重点对比 JDK 1.7 和 1.8 的实现差异，理解为什么 1.8 用 synchronized 替代 ReentrantLock（锁升级优化）。CAS + synchronized 的混合使用是面试亮点。'),
('什么是微服务架构？', '微服务架构是将单一应用程序开发为一组小型服务的方法。', 1, false, 7340, 510, 700, '微服务架构是将单一应用程序开发为一组小型服务的方法，每个服务运行在独立进程中，服务间通过轻量级机制（通常是 HTTP RESTful API）通信。核心特点：服务独立部署、技术栈可异构、去中心化治理、容错设计。常见组件：服务注册与发现、配置中心、网关、熔断器、链路追踪。', '微服务是后端架构面试的热门话题。需要理解微服务的核心思想和常见组件，同时也要了解微服务的挑战（分布式事务、服务治理、数据一致性等）。面试中常结合 Spring Cloud 或 Dubbo 来考察。'),
('Redis 缓存穿透、击穿、雪崩的解决方案？', '缓存穿透：布隆过滤器；缓存击穿：互斥锁；缓存雪崩：过期时间加随机值。', 2, false, 10800, 800, 1100, '缓存穿透：查询不存在的数据，缓存和数据库都没有。解决方案：布隆过滤器、缓存空值。缓存击穿：热点 key 过期瞬间大量请求打到数据库。解决方案：互斥锁、热点 key 永不过期。缓存雪崩：大量 key 同时过期。解决方案：过期时间加随机值、多级缓存、熔断降级。', '缓存三大问题是 Redis 面试必考题。需要清晰区分三种问题的场景和解决方案，面试官常追问具体实现细节。建议结合实际项目经验说明如何预防和处理这些问题。'),
('Go 语言中的 Goroutine 和 Channel 有什么特点？', 'Goroutine 是 Go 语言的轻量级线程；Channel 是 Goroutine 间通信的管道。', 2, false, 6230, 450, 620, 'Goroutine 是 Go 语言的轻量级线程（协程），初始栈仅 2KB 可动态扩展，由 Go 运行时调度而非操作系统。Channel 是 Goroutine 间通信的管道，遵循 CSP 模型（不要通过共享内存来通信，而要通过通信来共享内存）。Channel 分为无缓冲和有缓冲两种，支持 select 多路复用。', 'Goroutine 和 Channel 是 Go 语言的核心特性。面试中常考调度模型（GMP 模型）、Channel 的底层实现（hchan 结构体）、select 的随机性等。需要理解 Go 的并发哲学和 CSP 模型。'),
('React 中 useEffect 的执行时机是什么？', 'useEffect 在组件渲染到屏幕之后异步执行。', 2, false, 5430, 380, 510, 'useEffect 在组件渲染到屏幕之后异步执行。useLayoutEffect 在 DOM 更新后同步执行，阻塞视觉更新。useEffect 的清理函数在组件卸载或下次 effect 执行前运行。依赖数组为空时只在挂载时执行一次，不传依赖数组则每次渲染都执行。', 'useEffect 是 React Hooks 的核心。需要理解其与 useLayoutEffect 的执行时机差异、清理函数的执行顺序、依赖数组的正确设置方式。闭包陷阱是常见面试追问点。'),
('Python 中 GIL 是什么？', 'GIL 是 CPython 中的全局解释器锁，确保同一时刻只有一个线程执行 Python 字节码。', 2, false, 5890, 410, 560, 'GIL（Global Interpreter Lock）是 CPython 中的全局解释器锁，确保同一时刻只有一个线程执行 Python 字节码。GIL 的存在使得 Python 多线程无法利用多核 CPU。解决方案：使用多进程（multiprocessing）、使用 C 扩展释放 GIL、使用 asyncio 异步编程。Python 3.2+ 改进了 GIL 的调度策略。', 'GIL 是 Python 面试的经典问题。需要理解 GIL 存在的原因（内存管理不是线程安全的）以及对性能的影响。面试常追问多线程 vs 多进程的选择、GIL 对 I/O 密集型 vs CPU 密集型任务的不同影响。'),
('C++ 中智能指针有哪些？', 'C++11 引入了 unique_ptr、shared_ptr、weak_ptr 三种智能指针。', 2, false, 5120, 360, 490, 'unique_ptr：独占所有权，不可复制只能移动，零开销抽象。shared_ptr：共享所有权，内部引用计数，最后一个 shared_ptr 销毁时释放资源。weak_ptr：弱引用，不增加引用计数，用于解决 shared_ptr 循环引用问题。推荐使用 make_unique 和 make_shared 创建智能指针。', '智能指针是 C++11 的核心特性。需要理解三种指针的所有权语义、引用计数的线程安全性、循环引用的解决方案。面试常追问 unique_ptr 的实现原理和移动语义。'),
('什么是数据库事务的 ACID 特性？', 'ACID 是数据库事务的四个特性：原子性、一致性、隔离性、持久性。', 1, false, 8760, 610, 840, '原子性（Atomicity）：事务中的操作要么全部成功，要么全部回滚，通过 undo log 实现。一致性（Consistency）：事务执行前后数据库处于一致状态，由业务约束保证。隔离性（Isolation）：并发事务之间互不干扰，通过锁和 MVCC 实现，四种隔离级别：读未提交、读已提交、可重复读、串行化。持久性（Durability）：事务提交后数据永久保存，通过 redo log 实现。', 'ACID 是数据库基础必考题。需要深入理解每个特性的实现机制（undo log、redo log、MVCC），而不仅仅是定义。面试常追问 MySQL 的四种隔离级别和各自解决的问题（脏读、不可重复读、幻读）。');

INSERT INTO question_bank_question (bank_id, question_id) VALUES
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10),
(1, 11), (1, 12), (1, 13), (1, 14), (1, 15),
(2, 1), (2, 2), (2, 3), (2, 7), (2, 13),
(3, 1), (3, 2), (3, 13),
(4, 4), (4, 12), (4, 13),
(5, 6), (5, 11),
(6, 5), (6, 7),
(7, 8), (7, 19),
(8, 9), (8, 15),
(9, 6), (9, 7),
(10, 6),
(11, 11), (11, 14),
(12, 10), (12, 11),
(13, 10), (13, 19),
(14, 12),
(15, 11), (15, 14), (15, 15);

INSERT INTO question_tag (question_id, tag_id) VALUES
(1, 1), (1, 12), (1, 13),
(2, 1), (2, 13),
(3, 1),
(4, 1), (4, 14),
(5, 1), (5, 12),
(6, 4), (6, 5),
(7, 4),
(8, 2), (8, 19),
(9, 3), (9, 19),
(10, 7),
(11, 10), (11, 18),
(12, 9),
(13, 1), (13, 14),
(14, 5), (14, 6),
(15, 3), (15, 19),
(16, 15),
(17, 18),
(18, 16),
(19, 17),
(20, 2), (20, 19);
